export const SESSION_REPOSITORY = Symbol('SESSION_REPOSITORY');
export const TASK_REPOSITORY = Symbol('TASK_REPOSITORY');
export const DAILY_CHECK_REPOSITORY = Symbol('DAILY_CHECK_REPOSITORY');
export const SUBMISSION_REPOSITORY = Symbol('SUBMISSION_REPOSITORY');
export const FEEDBACK_REPOSITORY = Symbol('FEEDBACK_REPOSITORY');
export const REPORT_REPOSITORY = Symbol('REPORT_REPOSITORY');
export const ASSIGNMENT_USE_CASE = Symbol('ASSIGNMENT_USE_CASE');
export const STUDENT_NOTE_REPOSITORY = Symbol('STUDENT_NOTE_REPOSITORY');
