export const SESSION_REPOSITORY = Symbol('SESSION_REPOSITORY');
export const ASSIGNMENT_REPOSITORY = Symbol('ASSIGNMENT_REPOSITORY');
export const SUBMISSION_REPOSITORY = Symbol('SUBMISSION_REPOSITORY');
export const FEEDBACK_REPOSITORY = Symbol('FEEDBACK_REPOSITORY');
export const REPORT_REPOSITORY = Symbol('REPORT_REPOSITORY');
